import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

const Test: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>This is a test page.</h1>
      </main>

      <footer className={styles.footer}>This is a test footer.</footer>
    </div>
  );
};

export default Test;
