import { useEffect, useRef } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';

import useTorrent from '../../hooks/useTorrent';

import { Button, Link as UILink } from '@chakra-ui/react';

const Test: NextPage = () => {
  const outputElement = useRef<HTMLDivElement>(null);

  const { isDownloading, isReady, progress, download } = useTorrent({
    container: outputElement.current,
  });

  const handleClick = () => {
    download(
      'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent',
    );
  };

  useEffect(() => {
    if (outputElement.current && (isDownloading || isReady)) {
      //file.appendTo(outputElement.current);
    }
  }, [progress]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>This is a test page.</h1>
        <Button onClick={handleClick}>Download Torrent</Button>

        {isDownloading && !isReady && <div>Downloading: {progress}%</div>}

        <div id="video" ref={outputElement}></div>
      </main>

      <footer className={styles.footer}>This is a test footer.</footer>
    </div>
  );
};

export default Test;
